# Docs: <https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-dependency-updates>

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jetexe"
    assignees:
      - "jetexe"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jetexe"
    assignees:
      - "jetexe"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jetexe"
    assignees:
      - "jetexe"

  ---
  # V1 branch
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: v1
    schedule:
      interval: "weekly"
    reviewers:
      - "jetexe"
    assignees:
      - "jetexe"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: v1
    schedule:
      interval: "weekly"
    reviewers:
      - "jetexe"
    assignees:
      - "jetexe"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: v1
    schedule:
      interval: "weekly"
    reviewers:
      - "jetexe"
    assignees:
      - "jetexe"
