name: release

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate builder values
        id: values
        run: echo "::set-output name=version::`echo ${GITHUB_REF##*/} | sed -e 's/^[vV ]*//'`"

      - name: Build image
        run: |
          docker buildx build \
            --tag "jetexe/cookiecutter:${{ steps.values.outputs.version }}" \
            --tag "jetexe/cookiecutter:latest" \
            --build-arg "COOKIECUTTER_VERSION=${{ steps.values.outputs.version }}" \
            --file ./Dockerfile \
            --push \
            .